server:
  port: 9004
spring:
  application:
    name: project-C
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.10.61.171:5432/edu-admin
    username: dev
    password: mko0PL<.;?
  cloud:
    nacos:
      discovery:
        server-addr: 172.10.70.16:8848 #配置nacos地址
  sleuth:
    propagation:
      tag:
        whitelisted-keys:
          - transactiontrace-id
          - parent-node
    propagation-keys:
      - transactiontrace-id
      - parent-node
#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'